#+TITLE: Import labs to OpenedX Ginkgo 
#+AUTHOR: VLEAD
#+DATE: [2018-01-10 Wed]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document has steps to import the labs into OpenedX
  platform running =Ginkgo= version.

* Port labs to Openedx
  Follow below steps to import a lab into OpenedX platform
  running Ginkgo version. Below steps are well tested
  against a sample lab =Population Ecology Virtual Lab
  I=. Please follow the same procedure for the rest of the
  labs

  1. Visit the [[https://docs.google.com/spreadsheets/d/1JQRB_hGMcKkN05ZaEtgJpbi06k6OzP35m8xi9DhUMyI/edit#gid=367642649][excel sheet]] for all the lab information
  2. Select a lab from the [[https://docs.google.com/spreadsheets/d/1JQRB_hGMcKkN05ZaEtgJpbi06k6OzP35m8xi9DhUMyI/edit#gid=367642649][excel sheet]] against assignee
  3. Against selected lab pick =new_lab_id= (i.e biotech18)
     and make a request to [[http://lds-alpha.base4.vlabs.ac.in][LDS]] service to get the lab
     information. If =new_lab_id= is null use
     =old_lab_id=. Use below command to make a request to
     LDS with lab_id as =biotech18=
     #+BEGIN_EXAMPLE
     firefox http://lds-alpha.base4.vlabs.ac.in/labs?lab_id=biotech18
     #+END_EXAMPLE
     Above command must result a json record with lab
     information otherwise contact development team
  4. Use JSON information obtained from step(3) (i.e lab_name)
     and download the appropriate lab sources from the [[http://files.vlabs.ac.in/downloads/edx-tar-balls/][link]]
     #+BEGIN_EXAMPLE
     wget http://files.vlabs.ac.in/downloads/edx-tar-balls/open-edx-population-ecology-I-amrita.tar.gz
     #+END_EXAMPLE

  5. Access the Openedx URL
     #+BEGIN_EXAMPLE
     firefox http://10.2.57.25:18010
     #+END_EXAMPLE
  6. Use below given credentials mapped to your name and
     login into the OpenedX studio
     #+BEGIN_EXAMPLE
     honor@example.com -- > Sripathi,  Madhavi
     audit@example.com ---> Sravanthi M, Raghupathi
     verified@example.com --- > Sanchitha , Mrudhvika
     staff@example.com ---> Shiva, Balamma
     #+END_EXAMPLE
     - Note :: Passwords will be communicated in person
  7. After successful login, please click on =New Course=
     button to create new course and fill up the details as
     per obtained JSON information from step(3)
     
     - Course Name ::
                      This value should be the =lab_name=
                      obtained in step(3) start each word
                      with uppercase
                         
     - Organiation :: 
                      Virtual-Labs
                      
     - Course Number ::
                        This value should be the =lab_id=
                        obtained from step(3)
   
     - Course Run ::
                     Anytime

     - Note :: 
               If anything went wrong while creation of the
               course please inform to admin team
  8. Import the downloaded course
  9. Once course is successfully imported visit the course
  10. Change =lab_id= and =exp_id= (all should be in
      lowercase) in =Simulation= section of all the
      experiments
  11. Also change =lab_id= and =exp_id= (all should in
      lowercase) in all feedback integration sections (i.e
      both lab level and experiment level)
  12. Publish all the experiments in the course
  13. Once above steps are done export the course and
      download.
  14. Untar the exported course
      #+BEGIN_EXAMPLE
      cd ~
      tar -xvf course.js8WAY.tar.gz
      #+END_EXAMPLE
  15. Search for the lab_name in the organization
      =https://github.com/vlabs-on-openedx= and clone the repository
      #+BEGIN_EXAMPLE
      cd ~
      git clone https://github.com/vlabs-on-openedx/open-edx-population-ecology-I-amrita
      #+END_EXAMPLE
  16. Change directory to =open-edx-population-ecology-I-amrita=
      #+BEGIN_EXAMPLE
      cd open-edx-population-ecology-I-amrita
      #+END_EXAMPLE
  17. Create a tag
      #+BEGIN_EXAMPLE
      git tag -a v1.0.0 -m "release with old lab_id and exp_id"
      #+END_EXAMPLE
  18. Check whether tag created
      #+BEGIN_EXAMPLE
      git tag
      #+END_EXAMPLE
      Above step should list =v1.0.0= version
  19. Push the tag
      #+BEGIN_EXAMPLE
      git push origin v1.0.0
      #+END_EXAMPLE
  20. Draft the release notes in the github repository in
      =https://github.com/vlabs-on-openedx/open-edx-population-ecology-I-amrita=
      organization
  21. Rsync the exported course content into cloned
      repository
      #+BEGIN_EXAMPLE
      rsync -avz --progress courses/ open-edx-population-ecology-I-amrita/
      #+END_EXAMPLE

  22. Remove the course folder
      #+BEGIN_EXAMPLE
      cd ~
      rm -rf course
      #+END_EXAMPLE
      
  23. Change directory to
      =open-edx-population-ecology-I-amrita= and push
      changes to github
      #+BEGIN_EXAMPLE
      cd open-edx-population-ecology-I-amrita
      git add <files>
      git commit -m "Edited new lab_name and exp_ids"
      git push origin master
      #+END_EXAMPLE
  24. Update the status and hosted url in the [[https://docs.google.com/spreadsheets/d/1JQRB_hGMcKkN05ZaEtgJpbi06k6OzP35m8xi9DhUMyI/edit#gid=367642649][excel sheet]]
      against chosen lab
      - Note :: 
                Replace hosted_url http://<ip-address> with
                =https://vlabs.ac.in= domain





